function [M,C,N,Y] = computeDynamicMatrices(in1,in2,in3)
%COMPUTEDYNAMICMATRICES
%    [M,C,N,Y] = COMPUTEDYNAMICMATRICES(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Dec-2020 13:33:31

dq1 = in2(1,:);
dq2 = in2(2,:);
q1 = in1(1,:);
q2 = in1(2,:);
tau_1 = in3(1,:);
tau_2 = in3(2,:);
t2 = cos(q2);
t3 = sin(q2);
t4 = q1+q2;
t5 = cos(t4);
t6 = t2./2.0;
t7 = t6+1.0./3.0;
M = reshape([t2+5.0./3.0,t7,t7,1.0./3.0],[2,2]);
if nargout > 1
    C = reshape([dq2.*t3.*(-1.0./2.0),(dq1.*t3)./2.0,t3.*(dq1+dq2).*(-1.0./2.0),0.0],[2,2]);
end
if nargout > 2
    t8 = t5.*(9.81e+2./2.0e+2);
    N = [t8+cos(q1).*1.4715e+1;t8];
end
if nargout > 3
    Y = [tau_1;tau_2];
end
