function A = computeA(in1)
%COMPUTEA
%    A = COMPUTEA(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2019 19:27:13

A = reshape([-1.0,1.0,2.0,2.0],[2,2]);
