function dA = computedA(in1,in2)
%COMPUTEDA
%    DA = COMPUTEDA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    19-Nov-2019 19:27:13

dA = reshape([0.0,0.0,0.0,0.0],[2,2]);
