function a = compute_a(in1)
%COMPUTE_A
%    A = COMPUTE_A(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    04-Nov-2019 15:37:45

x = in1(1,:);
y = in1(2,:);
t2 = x-2.0;
t3 = y-1.0;
a = [y;x+y+1.0;t2.^2+t3.^2-2.0];
